// This file is generated by screeps2go. DO NOT EDIT!
package runtime

import "syscall/js"

type Creep struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Room Room   `json:"room"`
}

func (c Creep) Value() js.Value {
	return js.Global().Get("Game").Get("creeps").Get(c.Name)
}

func (c Creep) Harvest(p0 js.Value) Error {
	return Error(c.Value().Call("harvest", p0).Int())
}

func (c Creep) MoveTo(p0 js.Value) Error {
	return Error(c.Value().Call("moveTo", p0).Int())
}

func (c Creep) Say(p0 string, p1 bool) Error {
	return Error(c.Value().Call("say", p0, p1).Int())
}

func (c Creep) Suicide() Error {
	return Error(c.Value().Call("suicide").Int())
}

func (c Creep) Transfer(p0 js.Value, p1 string) Error {
	return Error(c.Value().Call("transfer", p0, p1).Int())
}

func (c Creep) Store() Store {
	return Store{CreepName: c.Name}
}
