// This file is generated by screeps2go. DO NOT EDIT!
package runtime

import "syscall/js"

type StructureSpawn struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (s StructureSpawn) Value() js.Value {
	return js.Global().Get("Game").Get("spawns").Get(s.Name)
}

func (s StructureSpawn) IsActive() bool {
	return s.Value().Call("isActive").Bool()
}

func (s StructureSpawn) SpawnCreep(p0 []BodyPart, p1 string) Error {
	return Error(s.Value().Call("spawnCreep", toInterfaceSlice(p0), p1).Int())
}
